#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Wed Jun 19 15:02:00 2024
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class playerPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: playerPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.BORDER_RAISED
        wx.Panel.__init__(self, *args, **kwds)
        self.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))

        playerSizer = wx.FlexGridSizer(1, 4, 1, 10)

        GameNumber = wx.StaticText(self, wx.ID_ANY, "63", style=wx.ALIGN_CENTER_HORIZONTAL)
        GameNumber.SetBackgroundColour(wx.Colour(255, 255, 255))
        GameNumber.SetForegroundColour(wx.Colour(47, 47, 79))
        GameNumber.SetFont(wx.Font(40, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        playerSizer.Add(GameNumber, 4, wx.ALIGN_CENTER | wx.ALL | wx.FIXED_MINSIZE, 1)

        namesSizer = wx.FlexGridSizer(2, 1, 0, 0)
        playerSizer.Add(namesSizer, 1, wx.EXPAND, 0)

        Sirname = wx.StaticText(self, wx.ID_ANY, "McFly-Jeebus", style=wx.ALIGN_CENTER_HORIZONTAL)
        Sirname.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        namesSizer.Add(Sirname, 1, wx.ALL, 4)

        firstNamePronounceSizer = wx.GridBagSizer(0, 0)
        namesSizer.Add(firstNamePronounceSizer, 1, wx.EXPAND, 0)

        FirstName = wx.StaticText(self, wx.ID_ANY, "Marty", style=wx.ALIGN_LEFT)
        FirstName.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        firstNamePronounceSizer.Add(FirstName, (0, 0), (1, 1), wx.ALIGN_CENTER | wx.ALL, 5)

        Pronounced = wx.StaticText(self, wx.ID_ANY, "Mart-EEEE", style=wx.ALIGN_RIGHT)
        Pronounced.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_SLANT, wx.FONTWEIGHT_BOLD, 0, ""))
        firstNamePronounceSizer.Add(Pronounced, (0, 1), (1, 1), wx.ALIGN_CENTER | wx.ALL, 5)

        grid_sizer_1 = wx.FlexGridSizer(3, 1, 0, 2)
        playerSizer.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 5)

        Goals = wx.StaticText(self, wx.ID_ANY, "5")
        Goals.SetFont(wx.Font(20, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(Goals, 0, 0, 0)

        Assists = wx.StaticText(self, wx.ID_ANY, "3")
        Assists.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_1.Add(Assists, 0, 0, 0)

        PIM = wx.StaticText(self, wx.ID_ANY, "12")
        PIM.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_SLANT, wx.FONTWEIGHT_BOLD, 0, ""))
        grid_sizer_1.Add(PIM, 0, 0, 0)

        firstNamePronounceSizer.AddGrowableCol(0)
        firstNamePronounceSizer.AddGrowableCol(1)

        namesSizer.AddGrowableRow(0)
        namesSizer.AddGrowableCol(0)

        self.SetSizer(playerSizer)

        self.Layout()
        # end wxGlade

# end of class playerPanel

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame")

        self.PlayerPanel = playerPanel(self, wx.ID_ANY)
        #playerSizer.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
